### ISSUE TITLE
Support for PHPUnit 7.0

### ISSUE THREAD

**Issue by Korri** [phpstan/phpstan-phpunit#12]
No sure what this involves, but because of the `composer.json` requirements, it is not installable at all right now if you are using PHPUnit 7.0 (which is the current stable release).

**Comment by ondrejmirtes** [comment]
Hi, it’s not the current stable release. It’s not tagged yet and according to the changelog, it will be released on February 2nd. So there’s no point in acting now, anything can change.

**Comment by Korri** [comment]
Oups, yeah my bad I read the php version instead of phpunit, sorry about that.
