### ISSUE TITLE
Analysis of `assertSame` cannot infer type if expected value is constant from symfony `Response` object

### ISSUE THREAD

**Issue by keulinho** [phpstan/phpstan-phpunit#133]
Since the phpstan update to 1.7.0, `assertSame` throws an error when used with symfony`s `Response::HTTP_*` constants.
As the error only appears for `assertSame` calls and not others e.g. `assertEquals` I think the error may lay in this extension instead of in phpstan itself.

## Error message
```
Parameter #1 $expected of method PHPUnit\Framework\Assert::assertSame() contains unresolvable type.
```

## How to reproduce
```php
use PHPUnit\Framework\TestCase;
use Symfony\Component\HttpFoundation\Response;

class Test extends TestCase
{
    public function testThrowsAnError(): void
    {
         $this->assertSame(Response::HTTP_OK, 200);   
    }

    public function testThrowsNoError(): void
    {
         $this->assertEquals(Response::HTTP_OK, 200);   
         $this->assertSame(\PDO::PARAM_BOOL, 5);   
    }
}
```

## Environment
PHP: 8.1.5
phpstan: 1.7.0
phpstan-phpunit: 1.1.1
phpunit: 9.5.20

Other extensions:
phpstan-symfony: 1.1.8
phpstan-doctrine: 1.3.5

**Comment by ondrejmirtes** [comment]
This is how the signature of `assertSame` looks like on that PHPUnit version: https://github.com/sebastianbergmann/phpunit/blob/12bc8879fb65aef2138b26fc633cb1e3620cffba/src/Framework/Assert.php#L1315-L1334

What this extension does is that it replaces the call with `Identical` expression for TypeSpecifier: https://github.com/phpstan/phpstan-phpunit/blob/e00da5f7e5c25cbfe6a39d69a8f6439b93307d98/src/Type/PHPUnit/Assert/AssertTypeSpecifyingExtensionHelper.php#L135-L140

I don't know why this error is reported right now. /cc @rvanvelzen

**Comment by keulinho** [comment]
Just double checked, when downgrading to phpstan 1.6.9 the error is not reported

**Comment by rvanvelzen** [comment]
I can't reproduce this locally. Could you share a small reproducing repository?

**Comment by keulinho** [comment]
I also tried to reproduce this in a standalone repo and was not able to do so.

Maybe this is some kind of auotloading issue in the original project. I will investigate further and will keep you updated. :v:

**Comment by ondrejmirtes** [comment]
Please open a new issue if you manage to reproduce it, thanks 😊

**Comment by keulinho** [comment]
Looking deeper into it this is even weirder, we have following assertions in a test case
```php
        $this->getBrowser()->request('GET', '/api/product/' . $id1);
        static::assertSame(Response::HTTP_OK, $this->getBrowser()->getResponse()->getStatusCode());

        $this->getBrowser()->request('GET', '/api/product/' . $id2);
        static::assertSame(Response::HTTP_OK, $this->getBrowser()->getResponse()->getStatusCode());

        $this->getBrowser()->request('DELETE', '/api/product/' . $id1);
        static::assertSame(Response::HTTP_NO_CONTENT, $this->getBrowser()->getResponse()->getStatusCode());

        $this->getBrowser()->request('DELETE', '/api/product/' . $id2);
        static::assertSame(Response::HTTP_NO_CONTENT, $this->getBrowser()->getResponse()->getStatusCode());
 ```
 
 And only for the last line an error is thrown.
 
 The AST `arg` object passed to the `Identical` seems to be the same in all cases :thinking:

**Comment by rvanvelzen** [comment]
You're probably dealing with the same root cause as phpstan/phpstan#7324.

**Comment by keulinho** [comment]
Thanks for the hint. :v: 

Yes i can confirm it seems to be the same root cause, phpstan thinks that the `$this->getBrowser()->getResponse()->getStatusCode()` call is pure, at least it remembers the value of the call, but after calling `$this->getBrowser()->request()` the return value of the status code may change. 

Current workaround is to save the response object in a temp variable as then the `getStatusCode()` will be called on different objects/instances each time:
```php
        $this->getBrowser()->request('GET', '/api/product/' . $id1);
        $response = $this->getBrowser()->getResponse();
        static::assertSame(Response::HTTP_OK, $response->getStatusCode());

        $this->getBrowser()->request('GET', '/api/product/' . $id2);
        $response = $this->getBrowser()->getResponse();
        static::assertSame(Response::HTTP_OK, $response->getStatusCode());

        $this->getBrowser()->request('DELETE', '/api/product/' . $id1);
        $response = $this->getBrowser()->getResponse();
        static::assertSame(Response::HTTP_NO_CONTENT, $response->getStatusCode());

        $this->getBrowser()->request('DELETE', '/api/product/' . $id2);
        $response = $this->getBrowser()->getResponse();
        static::assertSame(Response::HTTP_NO_CONTENT, $response->getStatusCode());
```
