### ISSUE TITLE
Check for assertSame to assertNull

### ISSUE THREAD

**Issue by gemal** [phpstan/phpstan-phpunit#136]
would it be possible to support checking for:

```
$expected = null;
$this->assertSame($expected, $result);
```

that should be:
```
$this->assertNull($result);
```

?

**Comment by ondrejmirtes** [comment]
There was some discussion about this, and we decided only that `$this->assertSame(null, $result);` is worth reporting (and that's already been done for some time).

See: https://github.com/phpstan/phpstan-phpunit/pull/128
