### ISSUE TITLE
ensure use of assertInstanceOf

### ISSUE THREAD

**Issue by arderyp** [phpstan/phpstan-phpunit#139]
Example

`$this->assertSame(MyClass::class, get_class($object));`

should be changed to

`$this->assertInstanceOf(MyClass::class, $object);`

This is similar to the existing rule about using

`$this->assertCount(5, $array);`

instead of

`$this->assertSame(5, count($array));`

**Comment by ondrejmirtes** [comment]
They are not equivalent.
