### ISSUE TITLE
False positive for array assertions

### ISSUE THREAD

**Issue by amorimjuliana** [phpstan/phpstan-phpunit#146]
# Bug report

I started getting an error after updating my project dependency versions to:
- phpstan/phpstan: 1.9.1
- phpstan/phpstan-phpunit: 1.2.2

### Code snippet that reproduces the problem

I couldn't reproduce this with the playground because of the extension, but here is an example of a simple class:

```php
final class DummyObject
{
    /** @var array<string, int> */
    private array $patterns = [];

    /**
     * @return array<string, int>
     */
    public function getValues(): array
    {
        return $this->patterns;
    }

    /**
     * @return $this
     */
    public function addValue(string $name, int $value): self
    {
        $this->patterns[$name] = $value;

        return $this;
    }
}
````

And here is the test:

```php
$object = new DummyObject();

self::assertEmpty($object->getValues());

$object->addValue('foo', 1);

$values = $object->getValues();

self::assertCount(1, $values);
self::assertArrayHasKey('foo', $values);
````

### Expected output

All tests should pass, but I get the message `Call to static method PHPUnit\Framework\Assert::assertArrayHasKey() with 'foo', and array{} will always evaluate to false.`

### Did PHPStan help you today? Did it make you happy in any way?

I can't help telling you guys are the best and that my code gets a thousand times better on every update. And you help me find bugs I didn't realize I'd introduced. I'm happy to use and contribute every time I can :)

**Comment by ondrejmirtes** [comment]
Thank you very much for your kind words! :) I don't know why it started happening for you in 1.9.0, but it's kind of expected, see: https://phpstan.org/blog/remembering-and-forgetting-returned-values

Your options are:

1) Put `@phpstan-impure` in PHPDoc above your `addValue` method.
2) Turn off this option: https://phpstan.org/config-reference#rememberpossiblyimpurefunctionvalues

**Comment by amorimjuliana** [comment]
Oh, thank you. I  didn't know about this option. Sorry to bother you :)
