### ISSUE TITLE
Property MyType&PHPUnit\Framework\MockObject\MockObject does not accept PHPUnit\Framework\MockObject\MockObject

### ISSUE THREAD

**Issue by phanan** [phpstan/phpstan-phpunit#15]
Hello,

I'm trying our PHPStan with PHPUnit extension and can't seem to make it work. 

```php
class SampleTest {
    /** @var MockObject|MyType */
    private $obj;

    protected function setUp()
    {
        $this->obj = $this->createMock(MyType::class);
    }
}
```

When I run PHPStan against the code above with `-l max`, it complains about line 7:

```
Property SampleTest::$obj (MyType&PHPUnit\Framework\MockObject\MockObject) does not accept PHPUnit\Framework\MockObject\MockObject.
```

Am I doing anything wrong? Using phpstan/phpstan ^0.9.2 and phpstan/phpstan-phpunit ^0.9.4.

(Please note that above is the reduced version of the code, not an exact copy).

**Comment by ondrejmirtes** [comment]
Hi, I suspect you don't have  the extension installed, from the README:

And include extension.neon in your project's PHPStan config:

```
includes:
	- vendor/phpstan/phpstan-phpunit/extension.neon
```

**Comment by phanan** [comment]
Hello,

Actually I do have a `phpstan.neon` at the project root, which says:

```
includes:
	- vendor/phpstan/phpstan-phpunit/extension.neon
    - vendor/phpstan/phpstan-phpunit/rules.neon
    - vendor/phpstan/phpstan-phpunit/strictRules.neon
```

**Comment by phanan** [comment]
OK, if I specify the config file then it works:

```bash
vendor/bin/phpstan analyse -l 4 -c phpstan.neon app/Tests/PHPStanTest.php

1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] No errors
```

As you can see, the config file is at the root dir. Any guess why it's not picked up automatically?

**Comment by lookyman** [comment]
Because that feature is currently in master only. It will most likely be released in the next version.

**Comment by phanan** [comment]
💯 , thanks. I'll see myself out.
