### ISSUE TITLE
Add an option to check for non static dataprovider even without deprecation rules

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-phpunit#162]
I saw https://github.com/phpstan/phpstan-phpunit/pull/151 was added by @villfa to check for non static data provider.
But I don't have the check on my project.

If I understand correctly, it's only active if https://github.com/phpstan/phpstan-deprecation-rules is installed.
But I'd like to have this rule even if I don't use the deprecation-rules package.

Currently stricter analysis (https://phpstan.org/config-reference#stricter-analysis) with PHPStan is possible 
- By installing the strict-rules packages
- By enabling manually some extra config options.

I'd like the same for the non-static check, ie: a config option to enable this rules (which would be automatically set to true if https://github.com/phpstan/phpstan-deprecation-rules is installed).

Is it possible ?
Is it already possible and I miss something ?

Thanks

**Comment by ondrejmirtes** [comment]
It's a deprecation -> use the deprecation-rules package. I don't see why not.
