### ISSUE TITLE
Usage of a method in the @dataProvider docblock is not being recognized

### ISSUE THREAD

**Issue by MetalArend** [phpstan/phpstan-phpunit#172]
Versions:

- phpstan/phpstan                        1.10.7    PHPStan - PHP Static Analysis Tool
- phpstan/phpstan-doctrine               1.3.37    Doctrine extensions for PHPStan
- phpstan/phpstan-phpunit                1.3.10    PHPUnit extensions and rules for PHPStan
- phpstan/phpstan-strict-rules           1.5.0     Extra strict and opinionated rules for PHPStan
- phpstan/phpstan-symfony                1.2.21    Symfony Framework extensions and rules for PHPStan

I get the error `Method xxx is unused.` in PHPStan Pro, while the method is being used in the `@dataProvider`. I'm not entirely sure the phpstan-phpunit plugin is actually being loaded in the PHPStan editor, but it is the exact same issue.

Should this work, or am I supposed to tell PHPStan to not bother about it?

https://phpstan.org/r/54b2df28-60c6-4e12-bd0d-add9835ef91b

**Comment by ondrejmirtes** [comment]
Data provider must be public and static. See: https://github.com/sebastianbergmann/phpunit/issues/5115

**Comment by MetalArend** [comment]
Oh man, thanks for being so cool about me wasting your time like this. Thanks!
