### ISSUE TITLE
Static dataProviders are detected as unused

### ISSUE THREAD

**Issue by pascalheidmann** [phpstan/phpstan-phpunit#188]
We are using `phpunit` 9.6 and are preparing for migrating to phpunit 10 which wants its `dataProvider`s to be static. Gladly phpunit supports static `dataProvider`s already in 9.6 (or even longer?). Sadly phpstan is now detecting those `dataProvider`s as unused.

**Comment by ondrejmirtes** [comment]
Data provider can't be private.

**Comment by pascalheidmann** [comment]
@ondrejmirtes not sure about this. We are having several private `dataProvider`s and tests are running fine. But also PHPUnit 9.6 so not sure about phpunit 10.

**Comment by ondrejmirtes** [comment]
See: https://github.com/sebastianbergmann/phpunit/issues/5115

PHPUnit documentation states (https://docs.phpunit.de/en/10.1/writing-tests-for-phpunit.html#data-providers) - even in older versions:

> A data provider method must be `public`
