### ISSUE TITLE
`assertContains` always claiming it'll return true

### ISSUE THREAD

**Issue by simon-tma** [phpstan/phpstan-phpunit#193]
Reproduction case:

```php
        $this->assertContains('not in the list', new \ArrayObject([1]));
```

This generates the error:
> Call to method PHPUnit\Framework\Assert::assertContains() with 'not in the list' and ArrayObject<int, int> will always evaluate to true.

This is obviously incorrect and appears to happen whenever `$haystack` is a `\Traversable` rather than an array.

**Comment by axlon** [comment]
Seems to be caused by https://github.com/phpstan/phpstan-phpunit/pull/191

**Comment by pscheit** [comment]
maybe @villfa you can have a lookt at this? 😬
