### ISSUE TITLE
fix assertEquals(false into assertFalse(

### ISSUE THREAD

**Issue by gemal** [phpstan/phpstan-phpunit#194]
there is:
https://github.com/phpstan/phpstan-phpunit/blob/1.4.x/src/Rules/PHPUnit/AssertSameNullExpectedRule.php

if I made the same for:
`assertEquals(false, `
and turn it into `assertFalse(`

would that be accepted as a pull request?

**Comment by ondrejmirtes** [comment]
No, because they're not equivalent. `assertEquals` is for `== false`, but `assertFalse` is for `=== false`.

**Comment by gemal** [comment]
What about:
`$this->assertEquals(null, $test);` to `$this->assertNull($test);`
and
`$this->assertEquals(true, $test);` to `$this->assertTrue($test);`
and
`$this->assertEquals(10, count($test));` to `$this->assertCount(10, $test);`
would those apply for a pull request?

**Comment by ondrejmirtes** [comment]
I'd accept disallowing assertEquals completely and promoting assertSame instead, in phpstan-strict-rules. Similar to what https://github.com/phpstan/phpstan-strict-rules/blob/1.5.x/src/Rules/DisallowedConstructs/DisallowedLooseComparisonRule.php does.

**Comment by ondrejmirtes** [comment]
If you rewrite assertEquals about count to assertSame, the existing rule about changing assertSame to assertCount kicks in.
