### ISSUE TITLE
Narrow type on assertCount to non-empty-*

### ISSUE THREAD

**Issue by michalbundyra** [phpstan/phpstan-phpunit#204]
As noted here https://github.com/phpstan/phpstan-phpunit/issues/54#issuecomment-946069516

```php
Assert::assertCount(1, $array);
```

Not sure if it is possible to implement narrowing type to non-empty-* here.
This would be very helpful, so we do not need to add assertNotEmpty assertion.

Thanks

**Comment by ondrejmirtes** [comment]
Yeah, we can rewrite that to `count($array) === 1`.

**Comment by michalbundyra** [comment]
Done via https://github.com/phpstan/phpstan-phpunit/commit/d5242a59d035e46774f2e634b374bc39ff62cb95
