### ISSUE TITLE
Rule to enforce class naming

### ISSUE THREAD

**Issue by cs278** [phpstan/phpstan-phpunit#214]
Generally speaking PHPUnit looks for tests in files named `*Test.php`, which conventionally means the classes should be named `*Test`. Additionally I believe it is recommended/required (I cannot find docs for this) that "tests" designed to be extended should be named `*TestCase`.

I propose adding rule to this extension which enforces that classes are named appropriately:

* If a concrete class extends `PHPUnit\Framework\TestCase` and it should be named `*Test` - could also enforce `final`?
* If an abstract class extends `PHPUnit\Framework\TestCase` it should be named `*TestCase`.

Ideally the rule would also enforce the file is named appropriately as well but that might be outside scope.

If this convention isn't followed and you don't explicitly tell PHPUnit your test files then tests are not run, potentially keeping the build passing because a number of tests are being silently ignored.

**Comment by ruudk** [comment]
I like this idea.

**Comment by ruudk** [comment]
Another one: all public non-static methods should have a `#[Test]` attribute or named like `test*`. It happened a few times we thought we had tests but they were not picked up.

**Comment by ruudk** [comment]
This could be a good starting point for the final / abstract part, or as inspiration: https://github.com/ergebnis/phpstan-rules/blob/main/src/Classes/FinalRule.php

**Comment by cs278** [comment]
@ruudk I've thrown a PR together implementing my proposal, your proposal for checking methods as well could be added as an additional rule.

**Comment by staabm** [comment]
since I also stumbled recently over the "name your abstract test class" with a "TestCase" suffix, I really like this proposal.

**Comment by ondrejmirtes** [comment]
Hey, this isn't generally applicable. The way PHPUnit looks for test files is configurable. It's just that it usually looks like this:

```
<directory suffix="Test.php">
```

I feel like these suggested rules are too opinionated for the general audience.

**Comment by cs278** [comment]
Damn, I'd completely forgotten this was even configurable.
