### ISSUE TITLE
How to use the plugin when installing PHPStan as a phar?

### ISSUE THREAD

**Issue by Aerendir** [phpstan/phpstan-phpunit#23]
I'm trying to include [Phive](https://github.com/phar-io/phive) in my workflow to make easier to manage dependencies like PHPStan that are mandatory but that can lead to conflicts in Composer, so using them as phar is easier and also, in my opinion, more correct  as they are not strictly required to make any library to work.

Apart from the theoric discussion about their inclusion in composer.json or not, I want to use Phive and so I need to use PHPStan as a phar.

But, once I've downloaded it, how can I integrate plugins?

I'm posting this question here, but it relates to all other plugins (as I'm using others too...).

Any guidance about this is welcome.

PS

I think this is also related to the issue opened by @Soullivaneuh here https://github.com/phpstan/phpstan-phpunit/issues/11

**Comment by JanTvrdik** [comment]
See https://github.com/phpstan/phpstan/search?q=phive&type=Issues
