### ISSUE TITLE
Mocking multiple types

### ISSUE THREAD

**Issue by Stadly** [phpstan/phpstan-phpunit#31]
When mocking multiple types, the return type is not an intersection type.

**Example**
```php
$a = $this->createMock([\Foo::class, \Bar::class]);
```

**Current behavior**
PHPStan treats `$a` as a `PHPUnit\Framework\MockObject\MockObject`.

**Expected behavior**
PHPStan treats `$a` as a `Foo&Bar&PHPUnit\Framework\MockObject\MockObject`.

**Comment by Stadly** [comment]
Any news on this?

**Comment by Tobion** [comment]
> Passing an array of interface names to createMock() for creating a test double that implements multiple interfaces is deprecated and will no longer be supported in PHPUnit 9.

So this issue seems obsolete.

**Comment by ondrejmirtes** [comment]
Great to hear! So everyone with this issue should no longer use this functionality really.
