### ISSUE TITLE
Support for PHPUnit 8

### ISSUE THREAD

**Issue by henrikthesing** [phpstan/phpstan-phpunit#42]
PHPUnit 8 was released on 1st of february (https://phpunit.de/announcements/phpunit-8.html). phpstan-phpunit currently can not be used in projects that use phpunit version 8.

- add support for phpunit 8
- update dependency to phpunit/phpunit: "^8.0" in composer.json

**Comment by ondrejmirtes** [comment]
Hi, there's nothing in composer.json blocking the PHPUnit 8 support. There's only conflict with < 7.0.

**Comment by henrikthesing** [comment]
The restriction to phpunit/phpunit: "^7.0" in the require-dev part of the composer json will prevent composer from installing the current phpstan-phpunit version. See https://semver.mwl.be/#?package=phpunit%2Fphpunit&version=%5E7.0&minimum-stability=stable

**Comment by ondrejmirtes** [comment]
`require-dev` is only for dev purposes - it should not affect users of this extension.

**Comment by henrikthesing** [comment]
Yes, you are right. I think I have to investigate, why this dependency is causing problems in my case. Thank you.
