### ISSUE TITLE
False assertSame

### ISSUE THREAD

**Issue by ro0NL** [phpstan/phpstan-phpunit#43]
```
Call to static method PHPUnit\Framework\Assert::assertSame() with array(1, '2') and array(1) will always evaluate to false.
```

for 

```php
self::assertSame([1], $visited);
self::assertFalse($collection->contains(2));
self::assertSame([1, '2'], $visited);
```

however $visited is a reference, and my tests are passing. Im quite annoyed by these assumptions :(

How to solve? I cant workaround it using local `@var mixed $visited` annotation.. :(

**Comment by ro0NL** [comment]
this does work

```php
self::assertSame([1], $visited);
self::assertFalse($collection->contains(2));
/** @var mixed $visited2 */
$visited2 = $visited;
self::assertSame([1, '2'], $visited2);
```

 but doesnt make sense :D

**Comment by ondrejmirtes** [comment]
Yeah, references are hard. The code isn't obvious for human either and it's hard for static analyser to reason about.

**Comment by ro0NL** [comment]
Understood. Im just trying to tell PHPStan "the value is mixed", regardless of what it thinks from analyse.

**Comment by ro0NL** [comment]
https://github.com/phpstan/phpstan-phpunit/issues/25#issuecomment-411048592 could be a trick, not sure if you think it's valid?

**Comment by alexander-schranz** [comment]
Not sure if its the same issue but I have the following code:

```php
        $model = $this->getExcerptInstance();
        $this->assertNull($model->getExcerptImage());
        $model->setExcerptImage(['id' => 1]);
        $this->assertSame(['id' => 1], $model->getExcerptImage());
```

which ends with:

> Call to method PHPUnit\Framework\Assert::assertSame() with array('id' => 1) and null will always evaluate to false.

Its because phpstan saves `$this->assertNull` for getExcerptImage. Without that line it works as expected.

**Comment by VincentLanglet** [comment]
With 
```
$this->assertNull($foo);
$model->doFoo();
$this->assertSame(true, $foo);
```
It's easy to add a comment 
```
/* @var mixed $foo **/
```

But when we're using a getter
```
$this->assertNull($model->getFoo());
$model->doFoo();
$this->assertSame(true, $model->getFoo());
```
It would require to create two variable `$fooBefore` and `$fooAfter`.

Would it be possible to create something like a comment 
```
// @phpstan-reset $model->getFoo()
```
To forget the type ?

How does psalm resolve this @muglug ?

**Comment by ondrejmirtes** [comment]
@VincentLanglet I'm not a fan of commenting on two-year-old issues. Please open a new one and describe your problem in full length.
