### ISSUE TITLE
Support assertNotEmpty/assertEmpty

### ISSUE THREAD

**Issue by ntzm** [phpstan/phpstan-phpunit#54]
Passing a value to `assertNotEmpty`/`assertEmpty` doesn't tell phpstan that the value isn't/is empty

**Comment by ondrejmirtes** [comment]
Can you be more specific with a code sample?

**Comment by johnbillion** [comment]
Here's an example test:

```php
public function testFoo() : void {
	$file = file( 'file.txt' );

	self::assertNotEmpty( $file );
	self::assertCount( 10, $file );
}
```

The `assertCount()` line gets flagged as an error by PHPStan because `assertNotEmpty()` does not narrow the type of `$file` from `array|false` to `array`.

**Comment by johnbillion** [comment]
`self::assertIsArray( $file );` does correctly narrow the type.

**Comment by derrabus** [comment]
I just stumbled across this issue myself.

I have code that looks like this:

```php
$value = someFunctionThatReturnsStringOrNull();
self::assertNotEmpty($value);
someFunctionThatAcceptsStrings($value);
```

PHPStan complains that `$value` might be `null`. However, this case should haven been caught by the `assertNotEmpty()` call. If I replace `assertNotEmpty()` with `assertNotNull()`, the error is gone.

**Comment by greg0ire** [comment]
Note that `assertCount(1, $file)` does not narrow the type either.

**Comment by canvural** [comment]
Is this fixed with https://github.com/phpstan/phpstan-phpunit/commit/f5b7eb65d93d38673d4c9d8b0b20b6c601697778 ?

**Comment by ondrejmirtes** [comment]
Yes, should be, although I've written that mainly to fix wrong `@psalm-assert empty` annotation in PHPUnit, which would get much more annoying with PHPStan 1.9.0 soon to be released :)

**Comment by canvural** [comment]
> Yes, should be, although I've written that mainly to fix wrong `@psalm-assert empty` annotation in PHPStan, which would get much more annoying with PHPStan 1.9.0 soon to be released :)

Yeah I also experienced that while testing 1.9.x I was gonna mention it but you were faster [here.](https://github.com/phpstan/phpstan/issues/8186#issuecomment-1286688922)
