### ISSUE TITLE
Conflict with Phpstorm resolution.

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-phpunit#56]
I'm using 
```
"phpstan/phpstan": "0.12.*",
"phpstan/phpstan-phpunit": "0.12.*",
"phpunit/phpunit": "8.2.5",
```

I have warning from Phpstorm `'void' method 'getMockBuilder' result used` with the following code : 
```
$pdfGenerator = $this->getMockBuilder(PdfGenerator::class)->getMock();
```

When I Cmd + Click, I see Phpstorm are locating the getMockBuilder in `phpstan/phpstan-phpunit/stubs` (instead of inside Phpunit package, maybe he take the first one in lexical order) with the following annotation:
```
	/**
	 * @template T
	 * @phpstan-param class-string<T> $originalClassName
	 * @phpstan-return MockObject&T
	 */
	public function createConfiguredMock($originalClassName) {}
```
And theses annotations are not understood by Phpstorm.

Changing to 
```
	/**
	 * @template T
	 * @phpstan-param class-string<T> $originalClassName
	 * @phpstan-return MockObject&T
         * @return MockBuilder
	 */
	public function createConfiguredMock($originalClassName) {}
```
Fix the issue.

By the way, in Phpunit code, the annotations are
```
/**
     * Returns a builder object to create mock objects using a fluent interface.
     *
     * @param string|string[] $className
     *
     * @psalm-template RealInstanceType of object
     * @psalm-param class-string<RealInstanceType>|string[] $className
     * @psalm-return MockBuilder<RealInstanceType>
     */
    public function getMockBuilder($className): MockBuilder
    {
        $this->recordDoubledType($className);

        return new MockBuilder($this, $className);
    }
```

So the returnType/paramsType are added both with the psalm syntax and the regular syntax.

Shouldn't the regular syntax be used too in the stubs provided by phpstan ?

**Comment by ondrejmirtes** [comment]
Hi, instead, I’d like to have some good way of excluding those stubs in PhpStorm. Can you figure something out? 😊

**Comment by VincentLanglet** [comment]
> Hi, instead, I’d like to have some good way of excluding those stubs in PhpStorm. Can you figure something out? 😊

I have no clue about how doing it, but if I find, I'll sure tell you.

**Comment by lookyman** [comment]
You can mark directory as excluded. It appears to help.

**Comment by VincentLanglet** [comment]
> You can mark directory as excluded. It appears to help.

Since it's a vendor, every developer using `phpstan-phpunit` has to exclude this directory ; and they have to do this every time they install the package. That's not the best solution.

Having something like a `.phpstormignore` feature, or adding the correct @param/@return annotation would be great.

**Comment by lookyman** [comment]
> Since it's a vendor

Yea, that is a problem, I agree.

**Comment by ondrejmirtes** [comment]
I released new versions of phpstan-phpunit, phpstan-doctrine and phpstan-mockery where this should no longer be a problem. I renamed those files from `.php` to `.stub`.

**Comment by VincentLanglet** [comment]
@ondrejmirtes Thanks !
I think it should be the same for https://github.com/phpstan/phpstan-symfony and https://github.com/phpstan/phpstan-nette

**Comment by ondrejmirtes** [comment]
Done
