### ISSUE TITLE
PHPStan reports unresolvable type when mocking final classes

### ISSUE THREAD

**Issue by T2L** [phpstan/phpstan-phpunit#57]
Final classes can be mocked using https://github.com/dg/bypass-finals

See https://phpstan.org/r/522f80ff-4c85-4a2d-a760-32249fc5d9e1

**Comment by ondrejmirtes** [comment]
Create a [custom bootstrap file](https://github.com/phpstan/phpstan#bootstrap-file) for PHPStan and call `DG\BypassFinals::enable();` in it. It should work.

**Comment by T2L** [comment]
@ondrejmirtes thanks for the prompt reply! It does work. But I also have `ergebnis/phpstan-rules` and now it does not like that everything is not final https://github.com/ergebnis/phpstan-rules#classesfinalrule

**Comment by ondrejmirtes** [comment]
I guess you can't have both at the same time...

**Comment by T2L** [comment]
What about extending the default rule and allowing the combination of the final class with specifically `\PHPUnit\Framework\MockObject\MockObject` ?

**Comment by ondrejmirtes** [comment]
I guess you could persuade @localheinz to look for the “final” class information not in reflection but in the AST in his rule.

**Comment by T2L** [comment]
BTW, adding `DG\BypassFinals::enable();` to the phpstan bootstrap seems like create an issue:

```
Internal error: Could not write data to cache file /var/folders/lg/0bf6nwsd0qb4f6x5rcfnqjxh0000gn/T/phpstan/cache/PHPStan/8c/d5/8cd518059139430c676a0d3d19259c88507b0217.php.  
Run PHPStan with --debug option and post the stack trace to:                                                                                                                   
https://github.com/phpstan/phpstan/issues/new        
```
