### ISSUE TITLE
Support $this->assertIsString

### ISSUE THREAD

**Issue by amalricBzh** [phpstan/phpstan-phpunit#67]
Hi,

I have this code :

    $content = $client->getResponse()->getContent();
    $this->assertIsString($content);
    $this->assertJson($content);

phpstan throws an error: 

> Parameter #1 $actualJson of method PHPUnit\Framework\Assert::assertJson() expects string, string|false given.

I expect that phpstan understand that if `assertIsString($content)` passed, `$content` is a string, and phpstan should not throw an error.

My composer file: 

    "require-dev": {
        "phpstan/phpstan": "^0.11",
        "phpstan/phpstan-phpunit": "^0.11",
        [...]
    }

**Comment by ondrejmirtes** [comment]
Hi, upgrade to ^0.12, `assertIsString` is supported there.

You shouldn't have any problems upgrading to the latest versions. If you don't have time to fix newly reported errors now, you can take advantage of a feature called the baseline: https://medium.com/@ondrejmirtes/phpstans-baseline-feature-lets-you-hold-new-code-to-a-higher-standard-e77d815a5dff
