### ISSUE TITLE
Improve check for assertSame() instead of assertCount().

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-phpunit#68]
Actually we got an error for 
```
assertSame(1, count($variable))
```

Would it be possible to also get an error for
```
assertSame(1, $variable->count())
```
if $variable is `Countable` ?

**Comment by ondrejmirtes** [comment]
Yes, it would be really easy to implement it. This is the current rule: https://github.com/phpstan/phpstan-phpunit/blob/master/src/Rules/PHPUnit/AssertSameWithCountRule.php

**Comment by VincentLanglet** [comment]
@ondrejmirtes Indeed, it was not so hard, the PR is opened https://github.com/phpstan/phpstan-phpunit/pull/69 :)
