### ISSUE TITLE
Call to method method() on an unknown class  PHPUnit\Framework\MockObject\InvocationMocker.

### ISSUE THREAD

**Issue by williamdes** [phpstan/phpstan-phpunit#73]
https://travis-ci.org/github/williamdes/phpmyadmintest/jobs/692987893#L410

After updating to `0.12.9` `710` errors did appear, false positive or not @ondrejmirtes ?

**Comment by williamdes** [comment]
cc @VincentLanglet  

Maybe related to https://github.com/phpstan/phpstan-phpunit/commit/1d3cfe367482f247ab4ddd3e99cefa91efcbaf91

phpunit `9.1.5`

**Comment by VincentLanglet** [comment]
Test ci was only running on Phpunit ^7.0.

Fixed by https://github.com/phpstan/phpstan-phpunit/pull/74 
@ondrejmirtes

**Comment by ondrejmirtes** [comment]
Just tagged 0.12.10, thanks.
