### ISSUE TITLE
Discover constants from PHPUnit configuration file

### ISSUE THREAD

**Issue by christeredvartsen** [phpstan/phpstan-phpunit#76]
Not sure if this is covered elsewhere, but I can't seem to find any docs on the subject.

I'm analysing my tests, and I have specified a constant in the PHPUnit configuration file (as per the docs: https://phpunit.readthedocs.io/en/9.2/configuration.html):

```xml
<php>
  <const name="foo" value="bar"/>
</php>
```

This is not discovered by PHPStan. Is there some way I can configure PHPStan to look in this file for constants as well?

I'm triggering the run like this:

```
vendor/bin/phpstan analyse -l max tests
```

**Comment by ondrejmirtes** [comment]
Hi, currently the only way to discover global constants in PHPStan is described in the documentation: https://phpstan.org/user-guide/discovering-symbols#global-constants
