### ISSUE TITLE
Don't work Foo&PHPUnit_Framework_MockObject_MockObject

### ISSUE THREAD

**Issue by Mark-Sart** [phpstan/phpstan-phpunit#81]
Don't work comments Foo&PHPUnit_Framework_MockObject_MockObject and Foo&MockObject

```
/**
* @return Foo&MockObject
*/
private function createSomeMock()
{
    $mock = $this
        ->getMockBuilder(Foo::class)
        ->setMethodsExcept(['foo', 'bar'])
        ->setConstructorArgs([])
        ->getMock();

    return $mock;
}
```

phpstan error: `PHPDoc tag @return contains unresolvable type.`

phpstan version: `0.12.37`
phpstan-phpunit version: `0.12.16`

**Comment by ondrejmirtes** [comment]
Do you have `use PHPUnit\Framework\MockObject\MockObject` above the class?
What version of PHPUnit do you have?

**Comment by Mark-Sart** [comment]
> Do you have `use PHPUnit\Framework\MockObject\MockObject` above the class?
> What version of PHPUnit do you have?

Yes.
7.5.20

**Comment by ondrejmirtes** [comment]
I have the same version and it works for me right in PHPStan sources themselves: https://github.com/phpstan/phpstan-src/blob/86a3b5699a7baa45247bf3fe8665d17b73dfb69e/tests/PHPStan/Parser/CachedParserTest.php#L87

Please create a small reproducing repository so I can debug the problem for you.

**Comment by Mark-Sart** [comment]
Ok. I'm preparing repository.

**Comment by Mark-Sart** [comment]
https://github.com/Mark-Sart/phpstan-phpunit-issue

**Comment by ondrejmirtes** [comment]
Solved: https://github.com/Mark-Sart/phpstan-phpunit-issue/pull/1

**Comment by marksartdev** [comment]
I have some problems yet.
In general, it is work, but if I change my baseline I have error `PHPDoc tag @return contains unresolvable type.`
In my opinion, it happen when I have cash of target file and I change my base-line. But if I change target file or remove cache,
phpstan works correctly.

**Comment by ondrejmirtes** [comment]
Can you give me a set of steps to reproduce this on that repository?

**Comment by marksartdev** [comment]
On that repository phpstan work correct.

**Comment by ondrejmirtes** [comment]
So reproduce it 🤷

**Comment by marksartdev** [comment]
I'l try to reproduce it on test repository.
