### ISSUE TITLE
Support for methods added with addMethods phpunit function

### ISSUE THREAD

**Issue by lugus** [phpstan/phpstan-phpunit#87]
Hello, thank you for your work.

Reporting issue about the `onlyMethods` from `phpunit`, it looks than `phpstan-phpunit` do not check methods added with these method and raise an error.

When:

```
$fooMock = $this->getMockBuilder(\stdClass::class)
                ->addMethods(['hello'])
                ->getMock();
$fooMock->method('hello')
        ->willReturn('Hello PHPStan');
```

```
 ------ -----------------------------------------------------------------------------------------------
  Line   Tests/Unit/FooTest.php
 ------ -----------------------------------------------------------------------------------------------
  120    Trying to mock an undefined method hello() on class stdClass.
 ------ -----------------------------------------------------------------------------------------------
```

**Comment by VincentLanglet** [comment]
I just encountered this issue with the code
```
$object2 = $this->getMockBuilder(\stdClass::class)->addMethods(['addFooBar'])->getMock();
$object2->expects($this->once())->method('addFooBar')->with($instance);
```

Any recommendation @ondrejmirtes ?

**Comment by VincentLanglet** [comment]
I created a reproducer: https://github.com/phpstan/phpstan-phpunit/pull/93

**Comment by ondrejmirtes** [comment]
I don't understand the use-case. If you're adding methods to the mock that don't exist on the mocked class, you'll also get PHPStan errors where you're calling the passed object in production code. e.g. `Method addFooBar does not exist on stdClass.`. Isn't it better to define an interface that requires those methods to be implemented?

**Comment by VincentLanglet** [comment]
The usecase is 
```
$fieldDescription = $this->createMock(FieldDescriptionInterface::class);
$fieldDescription->expects($this->once())->method('getAssociationMapping')->willReturn(['fieldName' => 'fooBar']);
$fieldDescription->expects($this->once())->method('getParentAssociationMappings')->willReturn([]);

$instance = new \stdClass();
$object = $this->getMockBuilder(\stdClass::class)->setMethods(['addFooBar'])->getMock();
$object->expects($this->once())->method('addFooBar')->with($instance);

ObjectManipulator::addInstance($object, $instance, $fieldDescription);
```

Here, the method name `addFooBar` is dynamically generated because of the fieldName `'fooBar'`.
There is no and never will interface for this.

**Comment by lugosium** [comment]
Some situations where i use `addMethods`:

Some specific PDO driver functions e.g: https://www.php.net/manual/fr/pdo.pgsqlgetnotify.php
AWS class using `@method` phpdoc annotation e.g: https://github.com/aws/aws-sdk-php/blob/master/src/Athena/AthenaClient.php

**Comment by ondrejmirtes** [comment]
`@method` annotation is understood by PHPStan.

**Comment by VincentLanglet** [comment]
The issue of @lugus and all the error I get is because we're adding methods to `\stdClass`.
The purpose of mocking a stdClass and adding method is to avoid to create a class just for the tests.

Since no method exist for \stdClass, what do you think about ignoring the method check for a mock of `\stdClass` ? @ondrejmirtes

**Comment by lugosium** [comment]
> `@method` annotation is understood by PHPStan.

I was giving some use cases to reply your comment https://github.com/phpstan/phpstan-phpunit/issues/87#issuecomment-804066678, it's indeed ok for `@method`, but do you have any solutions for the `pgsqlGetNotify` function?

**Comment by mpoiriert** [comment]
I have other use case where a method expect an object with a specific interface (X), If the object implements another interface (Y) as well a specific method will be call. I want to test that if the object has the method of interface Y but don't implement the interface Y it will not be called.

**Comment by VincentLanglet** [comment]
This issue might be closed since `addMethods` is deprecated cf https://github.com/sebastianbergmann/phpunit/issues/5320 @ondrejmirtes

**Comment by ondrejmirtes** [comment]
Thanks!
