### ISSUE TITLE
phpunit assertInstanceOf (when validate variable type) is ignored after 1 line

### ISSUE THREAD

**Issue by slava-v** [phpstan/phpstan-phpunit#88]
I have a strange behaviour in tests. 

`phpstan` warns about the return type. Even if i already asserted for it's type 2 lines above. 

Is this correct behaviour ? If - yes then what would be the correct way to have this solved, only through variable ?

```php
class SurveyCancellationControllerTest extends ApiWebTestCase
{
    public function testCreateAction()
    {
        $this->getClient()->request('GET', '/de/');

        $this->assertInstanceOf(Response::class,  $this->getClientResponse());       
        // assert($this->getClientResponse() instanceof Response);                   //  <-- same behaviour with assert()
        $this->assertEquals(200, $this->getClientResponse()->getStatusCode());
        $this->assertEquals("OK content", $this->getClientResponse()->getContent()); // < -- Complains about this line
    }

    protected function getClientResponse(): ?Response
    {
        return $this->getClient()->getResponse();
    }
}

**Comment by ondrejmirtes** [comment]
You're relying on `$this->getClientResponse()` to always return the same thing which might not be true.

First save `$this->getClientResponse()` into a variable, assert that and then work with the variable.

**Comment by slava-v** [comment]
@ondrejmirtes, Hi, and thanks for quick reply, that's not happening often on github i would say.

... as I presumed, solution would be only through variable :(

I guess my expectations were slightly different.
When the method is a getter of a data transfer object the behavior is unexpected i would say... 

Do you think we can do something about this. Maybe you could point to the right direction where i could take a look whether is possible to adapt the assertions and contribute if possible.

Thanks !

**Comment by ondrejmirtes** [comment]
This is a complicated topic, if I were to describe it (and essentially come up with the solution), I could implement it myself. But I want to tackle this some time in the future, so just stay tuned.
