### ISSUE TITLE
Do not depend on phpunit/phpunit

### ISSUE THREAD

**Issue by m-vo** [phpstan/phpstan-phpunit#89]
Could `phpunit/phpunit` be a dev dependency instead? Otherwise this produces problems with Symfony's `phpunit-bridge` where a certain version of phpunit will be installed lazily and now there are already other phpunit classes autoloaded.

**Comment by ondrejmirtes** [comment]
phpunit/phpunit isn't a dependency: https://github.com/phpstan/phpstan-phpunit/blob/58e52ad987ba571f69a8710eb907ad68e93ad977/composer.json#L8-L11

**Comment by m-vo** [comment]
Ah, sorry, my bad. I mistakenly opened it in the wrong repo :facepalm:.
