### ISSUE TITLE
support assert* functions

### ISSUE THREAD

**Issue by staabm** [phpstan/phpstan-phpunit#99]
phpunit supports a bunch of ["alias"-functions](https://github.com/sebastianbergmann/phpunit/blob/187407c87fbe7ee1455a1ef10e46e23fbd80860f/src/Framework/Assert/Functions.php) which can be used as a shorthand for the `Assert` methods

it would be great if this extension could support these.

in my concrete case, I am using `assertInstanceOf()` and phpstan does not recognize the type which get asserted and reports missing functionality after a `assertInstanceOf` call:

![grafik](https://user-images.githubusercontent.com/120441/122357933-74e06e80-cf54-11eb-91ac-cc7b2eb39e9e.png)

```php
final class UserIdentityVO 
{
    /**
     * Our primary key in database.
     *
     * @var int
     */
    public $userid;
}
```

**Comment by ondrejmirtes** [comment]
They were already supported, but only as non-namespaced ones. Which is how the functions used to look like in PHPUnit: https://github.com/sebastianbergmann/phpunit/blob/7.1.2/src/Framework/Assert/Functions.php

Fixed: https://github.com/phpstan/phpstan-phpunit/commit/8e11b1a1d0c8e0a7be3e49715c99a44c54b16803

**Comment by staabm** [comment]
thank you!!
